# Generated by Django 3.2 on 2021-09-30 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subscriber_name', models.CharField(max_length=200)),
                ('Subscriber_email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200)),
                ('Product_desc', models.CharField(max_length=300)),
                ('Product_price', models.IntegerField(max_length=200)),
                ('Special_offer', models.BooleanField(default=False)),
                ('Product_image', models.ImageField(upload_to='images')),
                ('Image_url', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200)),
                ('Product_desc', models.CharField(max_length=300)),
                ('Product_price', models.IntegerField(max_length=200)),
                ('Special_offer', models.BooleanField(default=False)),
                ('Product_image', models.ImageField(upload_to='images')),
                ('Image_url', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsBags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=200)),
                ('Product_desc', models.CharField(max_length=300)),
                ('Product_price', models.IntegerField(max_length=200)),
                ('Special_offer', models.BooleanField(default=False)),
                ('Product_image', models.ImageField(upload_to='images')),
                ('Image_url', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('PostalCode', models.CharField(max_length=255)),
                ('PhoneNo', models.IntegerField(max_length=11)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Django_app.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_app.order')),
                ('product2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_app.products2')),
                ('product_bag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_app.productsbags')),
            ],
        ),
    ]
