# Generated by Django 3.2 on 2021-09-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
