# Generated by Django 3.2 on 2021-09-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('PostalCode', models.CharField(max_length=255)),
                ('PhoneNo', models.IntegerField(max_length=11)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Django_app.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_app.order')),
            ],
        ),
    ]
