# Generated by Django 3.2 on 2021-09-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='PhoneNo',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
