# Generated by Django 3.2 on 2021-10-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0007_auto_20211002_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Image_url',
        ),
        migrations.RemoveField(
            model_name='products2',
            name='Image_url',
        ),
        migrations.RemoveField(
            model_name='productsbags',
            name='Image_url',
        ),
    ]
