# Generated by Django 3.2 on 2021-10-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0008_auto_20211002_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='products2',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Django_app.category'),
        ),
    ]
