# Generated by Django 3.2 on 2021-10-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0009_products2_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_bag',
        ),
    ]
