# Generated by Django 3.2 on 2021-10-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0012_alter_userprofile_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='PhoneNo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
