# Generated by Django 3.2 on 2021-11-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0013_alter_userprofile_phoneno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='ProductsBags',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
