# Generated by Django 3.2 on 2021-11-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app', '0014_auto_20211103_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products2',
            name='Product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phoneNo',
            field=models.IntegerField(null=True),
        ),
    ]
